default_platform(:ios)

platform :ios do
  desc "Build and upload a release build to TestFlight"
  lane :testflight do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_P8"],
      in_house: false
    )

    build_app(
      workspace: "Delta.xcworkspace",
      scheme: "Delta",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "build",
      clean: true,
      xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
